name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag offlineimap:$(date +%s)
    - name: Login to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quay.io/j1cken/offlineimap:$(date +%s)
    - name: Push to Quay.io
      run: docker push quay.io/j1cken/offlineimap:$(date +%s)
